--- #YAML:1.0
name:               xls2csv
version:            1.07
abstract:           A script that recodes a spreadsheet's charset and saves as CSV.
author:
    - Ken Prows <perl@xev.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Locale::Recode:       0
    Spreadsheet::ParseExcel:  0
    Spreadsheet::ParseExcel::FmtUnicode:  0
    Text::CSV_XS:         0
    Unicode::Map:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
